# Generated by Django 4.1.5 on 2023-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinsta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
