# Generated by Django 4.1.5 on 2023-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinsta', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
