# Generated by Django 4.1.5 on 2023-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinsta', '0003_profile_account_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
