version: "3.9"
services:
  app:
    build: dockerfile
    volumes:
      - .:/djinsta
      
    ports:
      - 8000:8000
    container_name: django_container
    command: gunicorn social_media_app.wsgi:application -c gunicorn_config.py
    environment:
      - REDIS_HOST=redis
      - DB_NAME=djinsta
      - DB_USER=root
      - DB_PASSWORD=lq11pnwifi
      - DB_PORT=3307
      - DB_HOST=db
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: lq11pnwifi
      MYSQL_DATABASE: djinsta
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis1
    ports:
      - 6379:6379
  nginx:
    image: nginx:latest
    container_name: nginx1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
