# Generated by Django 4.1.5 on 2023-02-03 06:03

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to=post.models.get_profile_url, verbose_name='Picture'),
        ),
    ]
