# Generated by Django 4.1.5 on 2023-02-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinsta', '0004_profile_followers'),
        ('post', '0002_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djinsta.profile'),
        ),
    ]
